//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{
    public partial class GioHang
    {
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher1;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher2;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher3;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher4;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher5;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher6;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher7;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher8;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher9;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher10;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher11;
        protected global::System.Web.UI.WebControls.LinkButton lnkVoucher12;
        protected global::System.Web.UI.WebControls.Panel pnlAppliedVoucher;
        protected global::System.Web.UI.WebControls.Label lblAppliedCode;
        protected global::System.Web.UI.WebControls.Label lblAppliedDiscount;
        protected global::System.Web.UI.WebControls.LinkButton btnRemoveVoucher;
        protected global::System.Web.UI.WebControls.Repeater rptCart;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblDiscount;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnCheckout;
    }
}
