//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{

	public partial class AdminDashboard
	{

		/// <summary>
		/// lblTotalOrders control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblTotalOrders;

		/// <summary>
		/// lblTotalProducts control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblTotalProducts;

		/// <summary>
		/// lblTotalUsers control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblTotalUsers;

		/// <summary>
		/// lblTotalRevenue control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblTotalRevenue;

		/// <summary>
		/// gvRecentProducts control.
		/// </summary>
		protected global::System.Web.UI.WebControls.GridView gvRecentProducts;
	}
}


