//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{

	public partial class AdminLogin
	{

		/// <summary>
		/// ScriptManager1 control.
		/// </summary>
		protected global::System.Web.UI.ScriptManager ScriptManager1;

		/// <summary>
		/// pnlError control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Panel pnlError;

		/// <summary>
		/// lblError control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblError;

		/// <summary>
		/// txtUsername control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtUsername;

		/// <summary>
		/// txtPassword control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtPassword;

		/// <summary>
		/// chkRememberMe control.
		/// </summary>
		protected global::System.Web.UI.WebControls.CheckBox chkRememberMe;

		/// <summary>
		/// btnLogin control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnLogin;
	}
}


