//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{

	public partial class AdminMaster
	{

		/// <summary>
		/// AdminHead control.
		/// </summary>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminHead;

		/// <summary>
		/// ScriptManager1 control.
		/// </summary>
		protected global::System.Web.UI.ScriptManager ScriptManager1;

		/// <summary>
		/// Logo control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Image Logo;

		/// <summary>
		/// btnLogout control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnLogout;

		/// <summary>
		/// PageTitle control.
		/// </summary>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder PageTitle;

		/// <summary>
		/// AdminMain control.
		/// </summary>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminMain;
	}
}


