//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{
	public partial class CategoryManagement
	{
		/// <summary>
		/// gvCategories control.
		/// </summary>
		protected global::System.Web.UI.WebControls.GridView gvCategories;

		/// <summary>
		/// txtNewCategoryName control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtNewCategoryName;

		/// <summary>
		/// txtNewDescription control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtNewDescription;

		/// <summary>
		/// txtNewIcon control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtNewIcon;

		/// <summary>
		/// btnAddCategory control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnAddCategory;
	}
}

