//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{
    public partial class OrderManagement
    {
        protected global::System.Web.UI.WebControls.Label lblPendingOrders;
        protected global::System.Web.UI.WebControls.Label lblProcessingOrders;
        protected global::System.Web.UI.WebControls.Label lblShippingOrders;
        protected global::System.Web.UI.WebControls.Label lblCompletedOrders;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.GridView gvOrders;
    }
}

