//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{

	public partial class ProductManagement
	{

		/// <summary>
		/// txtSearch control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtSearch;

		/// <summary>
		/// ddlCategory control.
		/// </summary>
		protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

		/// <summary>
		/// ddlSort control.
		/// </summary>
		protected global::System.Web.UI.WebControls.DropDownList ddlSort;

		/// <summary>
		/// btnAddProduct control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnAddProduct;

		/// <summary>
		/// btnBulkDelete control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnBulkDelete;

		/// <summary>
		/// btnExport control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnExport;

		/// <summary>
		/// gvProducts control.
		/// </summary>
		protected global::System.Web.UI.WebControls.GridView gvProducts;

		/// <summary>
		/// lblTotalProducts control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblTotalProducts;

		/// <summary>
		/// lblPageInfo control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Label lblPageInfo;

		/// <summary>
		/// pnlProductForm control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Panel pnlProductForm;

		/// <summary>
		/// txtProductName control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtProductName;

		/// <summary>
		/// ddlProductCategory control.
		/// </summary>
		protected global::System.Web.UI.WebControls.DropDownList ddlProductCategory;

		/// <summary>
		/// txtPrice control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtPrice;

		/// <summary>
		/// txtStock control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtStock;

		/// <summary>
		/// txtDescription control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox txtDescription;

		/// <summary>
		/// fuProductImage control.
		/// </summary>
		protected global::System.Web.UI.WebControls.FileUpload fuProductImage;

		/// <summary>
		/// ddlStatus control.
		/// </summary>
		protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

		/// <summary>
		/// btnSaveProduct control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Button btnSaveProduct;
	}
}

