//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop
{
    public partial class Reports
    {
        protected global::System.Web.UI.WebControls.Label lblMonthlyRevenue;
        protected global::System.Web.UI.WebControls.Label lblMonthlyOrders;
        protected global::System.Web.UI.WebControls.Label lblNewCustomers;
        protected global::System.Web.UI.WebControls.Label lblProductsSold;
        protected global::System.Web.UI.WebControls.GridView gvTopProducts;
    }
}

